In [5]:
# Prints a 1D array of numbers from 0 to 9 
import numpy as np
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#A 3×3 NumPy array of all Boolean value Trues
import numpy as np
array = np.ones(9, dtype = bool).reshape(3, 3)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
#Extract all odd numbers from array of 1 10
import numpy as np
array = np.arange(1, 11, 2)
print(array)

[1 3 5 7 9]


In [48]:
#Replace all odd numbers in an array of 1 10 with the value -1
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.where(arr%2==1, -1, arr)





array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [97]:
#Converts a 1D array to a 2D array with 2 rows
import numpy as np

a = np.arange(1, 11).reshape (2, 5)
print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
import numpy as np
a = np.arange(1, 17).reshape(4, 4)
b = np.arange(17, 33).reshape(4, 4)
c = np.vstack ((a, b))
d = np.dot(a, b)
sum = np.sum(d)

print("vertical stack is:", "\n",  c)

print("\n","sum of 2D arrays is:","\n", d)

print("\n","sum of array=", sum)




vertical stack is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

 sum of 2D arrays is: 
 [[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]

 sum of array= 13648
